name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkstyle
        run: make check_fmt
 
      - name: Run Array Tests
        run: make array_test
        
      - name: Run Quadratic Tests
        run: make quadratic_test
        
      - name: Run
        run: make try
